/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClinicasRouteImport } from './routes/clinicas'
import { Route as IndexRouteImport } from './routes/index'

const ClinicasRoute = ClinicasRouteImport.update({
  id: '/clinicas',
  path: '/clinicas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinicas': typeof ClinicasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinicas': typeof ClinicasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinicas': typeof ClinicasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clinicas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clinicas'
  id: '__root__' | '/' | '/clinicas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicasRoute: typeof ClinicasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clinicas': {
      id: '/clinicas'
      path: '/clinicas'
      fullPath: '/clinicas'
      preLoaderRoute: typeof ClinicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicasRoute: ClinicasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
