/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetoresRouteImport } from './routes/setores'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProcedimentosRouteImport } from './routes/procedimentos'
import { Route as ParcelasRouteImport } from './routes/parcelas'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as MasterRouteImport } from './routes/master'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuncionariosRouteImport } from './routes/funcionarios'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DisparadorRouteImport } from './routes/disparador'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AnamneseRouteImport } from './routes/anamnese'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterIndexRouteImport } from './routes/master/index'
import { Route as PacientesIdRouteImport } from './routes/pacientes.$id'
import { Route as MasterWhiteLabelRouteImport } from './routes/master/white-label'
import { Route as MasterSegmentosRouteImport } from './routes/master/segmentos'
import { Route as MasterDisparosRouteImport } from './routes/master/disparos'
import { Route as MasterClinicasRouteImport } from './routes/master/clinicas'
import { Route as MasterBotsRouteImport } from './routes/master/bots'
import { Route as MasterAutomacoesRouteImport } from './routes/master/automacoes'
import { Route as MasterAnunciosRouteImport } from './routes/master/anuncios'

const SetoresRoute = SetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosRoute = ProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelasRoute = ParcelasRouteImport.update({
  id: '/parcelas',
  path: '/parcelas',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosRoute = FuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DisparadorRoute = DisparadorRouteImport.update({
  id: '/disparador',
  path: '/disparador',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnamneseRoute = AnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasterRoute,
} as any)
const PacientesIdRoute = PacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PacientesRoute,
} as any)
const MasterWhiteLabelRoute = MasterWhiteLabelRouteImport.update({
  id: '/white-label',
  path: '/white-label',
  getParentRoute: () => MasterRoute,
} as any)
const MasterSegmentosRoute = MasterSegmentosRouteImport.update({
  id: '/segmentos',
  path: '/segmentos',
  getParentRoute: () => MasterRoute,
} as any)
const MasterDisparosRoute = MasterDisparosRouteImport.update({
  id: '/disparos',
  path: '/disparos',
  getParentRoute: () => MasterRoute,
} as any)
const MasterClinicasRoute = MasterClinicasRouteImport.update({
  id: '/clinicas',
  path: '/clinicas',
  getParentRoute: () => MasterRoute,
} as any)
const MasterBotsRoute = MasterBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => MasterRoute,
} as any)
const MasterAutomacoesRoute = MasterAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => MasterRoute,
} as any)
const MasterAnunciosRoute = MasterAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => MasterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/anamnese': typeof AnamneseRoute
  '/campanhas': typeof CampanhasRoute
  '/contatos': typeof ContatosRoute
  '/disparador': typeof DisparadorRoute
  '/financeiro': typeof FinanceiroRoute
  '/funcionarios': typeof FuncionariosRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/pacientes': typeof PacientesRouteWithChildren
  '/parcelas': typeof ParcelasRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/setores': typeof SetoresRoute
  '/master/anuncios': typeof MasterAnunciosRoute
  '/master/automacoes': typeof MasterAutomacoesRoute
  '/master/bots': typeof MasterBotsRoute
  '/master/clinicas': typeof MasterClinicasRoute
  '/master/disparos': typeof MasterDisparosRoute
  '/master/segmentos': typeof MasterSegmentosRoute
  '/master/white-label': typeof MasterWhiteLabelRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/master/': typeof MasterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/anamnese': typeof AnamneseRoute
  '/campanhas': typeof CampanhasRoute
  '/contatos': typeof ContatosRoute
  '/disparador': typeof DisparadorRoute
  '/financeiro': typeof FinanceiroRoute
  '/funcionarios': typeof FuncionariosRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/parcelas': typeof ParcelasRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/setores': typeof SetoresRoute
  '/master/anuncios': typeof MasterAnunciosRoute
  '/master/automacoes': typeof MasterAutomacoesRoute
  '/master/bots': typeof MasterBotsRoute
  '/master/clinicas': typeof MasterClinicasRoute
  '/master/disparos': typeof MasterDisparosRoute
  '/master/segmentos': typeof MasterSegmentosRoute
  '/master/white-label': typeof MasterWhiteLabelRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/master': typeof MasterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/anamnese': typeof AnamneseRoute
  '/campanhas': typeof CampanhasRoute
  '/contatos': typeof ContatosRoute
  '/disparador': typeof DisparadorRoute
  '/financeiro': typeof FinanceiroRoute
  '/funcionarios': typeof FuncionariosRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/pacientes': typeof PacientesRouteWithChildren
  '/parcelas': typeof ParcelasRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/setores': typeof SetoresRoute
  '/master/anuncios': typeof MasterAnunciosRoute
  '/master/automacoes': typeof MasterAutomacoesRoute
  '/master/bots': typeof MasterBotsRoute
  '/master/clinicas': typeof MasterClinicasRoute
  '/master/disparos': typeof MasterDisparosRoute
  '/master/segmentos': typeof MasterSegmentosRoute
  '/master/white-label': typeof MasterWhiteLabelRoute
  '/pacientes/$id': typeof PacientesIdRoute
  '/master/': typeof MasterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/anamnese'
    | '/campanhas'
    | '/contatos'
    | '/disparador'
    | '/financeiro'
    | '/funcionarios'
    | '/login'
    | '/master'
    | '/pacientes'
    | '/parcelas'
    | '/procedimentos'
    | '/relatorios'
    | '/setores'
    | '/master/anuncios'
    | '/master/automacoes'
    | '/master/bots'
    | '/master/clinicas'
    | '/master/disparos'
    | '/master/segmentos'
    | '/master/white-label'
    | '/pacientes/$id'
    | '/master/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/anamnese'
    | '/campanhas'
    | '/contatos'
    | '/disparador'
    | '/financeiro'
    | '/funcionarios'
    | '/login'
    | '/pacientes'
    | '/parcelas'
    | '/procedimentos'
    | '/relatorios'
    | '/setores'
    | '/master/anuncios'
    | '/master/automacoes'
    | '/master/bots'
    | '/master/clinicas'
    | '/master/disparos'
    | '/master/segmentos'
    | '/master/white-label'
    | '/pacientes/$id'
    | '/master'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/anamnese'
    | '/campanhas'
    | '/contatos'
    | '/disparador'
    | '/financeiro'
    | '/funcionarios'
    | '/login'
    | '/master'
    | '/pacientes'
    | '/parcelas'
    | '/procedimentos'
    | '/relatorios'
    | '/setores'
    | '/master/anuncios'
    | '/master/automacoes'
    | '/master/bots'
    | '/master/clinicas'
    | '/master/disparos'
    | '/master/segmentos'
    | '/master/white-label'
    | '/pacientes/$id'
    | '/master/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AnamneseRoute: typeof AnamneseRoute
  CampanhasRoute: typeof CampanhasRoute
  ContatosRoute: typeof ContatosRoute
  DisparadorRoute: typeof DisparadorRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FuncionariosRoute: typeof FuncionariosRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRouteWithChildren
  PacientesRoute: typeof PacientesRouteWithChildren
  ParcelasRoute: typeof ParcelasRoute
  ProcedimentosRoute: typeof ProcedimentosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SetoresRoute: typeof SetoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setores': {
      id: '/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof SetoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos': {
      id: '/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof ProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcelas': {
      id: '/parcelas'
      path: '/parcelas'
      fullPath: '/parcelas'
      preLoaderRoute: typeof ParcelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios': {
      id: '/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof FuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disparador': {
      id: '/disparador'
      path: '/disparador'
      fullPath: '/disparador'
      preLoaderRoute: typeof DisparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anamnese': {
      id: '/anamnese'
      path: '/anamnese'
      fullPath: '/anamnese'
      preLoaderRoute: typeof AnamneseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof MasterRoute
    }
    '/pacientes/$id': {
      id: '/pacientes/$id'
      path: '/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof PacientesIdRouteImport
      parentRoute: typeof PacientesRoute
    }
    '/master/white-label': {
      id: '/master/white-label'
      path: '/white-label'
      fullPath: '/master/white-label'
      preLoaderRoute: typeof MasterWhiteLabelRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/segmentos': {
      id: '/master/segmentos'
      path: '/segmentos'
      fullPath: '/master/segmentos'
      preLoaderRoute: typeof MasterSegmentosRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/disparos': {
      id: '/master/disparos'
      path: '/disparos'
      fullPath: '/master/disparos'
      preLoaderRoute: typeof MasterDisparosRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/clinicas': {
      id: '/master/clinicas'
      path: '/clinicas'
      fullPath: '/master/clinicas'
      preLoaderRoute: typeof MasterClinicasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/bots': {
      id: '/master/bots'
      path: '/bots'
      fullPath: '/master/bots'
      preLoaderRoute: typeof MasterBotsRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/automacoes': {
      id: '/master/automacoes'
      path: '/automacoes'
      fullPath: '/master/automacoes'
      preLoaderRoute: typeof MasterAutomacoesRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/anuncios': {
      id: '/master/anuncios'
      path: '/anuncios'
      fullPath: '/master/anuncios'
      preLoaderRoute: typeof MasterAnunciosRouteImport
      parentRoute: typeof MasterRoute
    }
  }
}

interface MasterRouteChildren {
  MasterAnunciosRoute: typeof MasterAnunciosRoute
  MasterAutomacoesRoute: typeof MasterAutomacoesRoute
  MasterBotsRoute: typeof MasterBotsRoute
  MasterClinicasRoute: typeof MasterClinicasRoute
  MasterDisparosRoute: typeof MasterDisparosRoute
  MasterSegmentosRoute: typeof MasterSegmentosRoute
  MasterWhiteLabelRoute: typeof MasterWhiteLabelRoute
  MasterIndexRoute: typeof MasterIndexRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterAnunciosRoute: MasterAnunciosRoute,
  MasterAutomacoesRoute: MasterAutomacoesRoute,
  MasterBotsRoute: MasterBotsRoute,
  MasterClinicasRoute: MasterClinicasRoute,
  MasterDisparosRoute: MasterDisparosRoute,
  MasterSegmentosRoute: MasterSegmentosRoute,
  MasterWhiteLabelRoute: MasterWhiteLabelRoute,
  MasterIndexRoute: MasterIndexRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

interface PacientesRouteChildren {
  PacientesIdRoute: typeof PacientesIdRoute
}

const PacientesRouteChildren: PacientesRouteChildren = {
  PacientesIdRoute: PacientesIdRoute,
}

const PacientesRouteWithChildren = PacientesRoute._addFileChildren(
  PacientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AnamneseRoute: AnamneseRoute,
  CampanhasRoute: CampanhasRoute,
  ContatosRoute: ContatosRoute,
  DisparadorRoute: DisparadorRoute,
  FinanceiroRoute: FinanceiroRoute,
  FuncionariosRoute: FuncionariosRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRouteWithChildren,
  PacientesRoute: PacientesRouteWithChildren,
  ParcelasRoute: ParcelasRoute,
  ProcedimentosRoute: ProcedimentosRoute,
  RelatoriosRoute: RelatoriosRoute,
  SetoresRoute: SetoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
